### ISSUE TITLE
ModuleNotFoundError: No module named 'pyvista'

### ISSUE THREAD

**Issue by Turbomichi** [kmarchais/blender-tpms#1]
Hello,

On Windows 11 and Blender 4.0.2 I get an ModuleNotFoundError. The pyvista module can not be found and is not installed automatically. Thanks

**Comment by kmarchais** [comment]
Hello,

Can you try to run the following code in the Scripting tab in Blender?
(`Scripting > New > Copy/Paste the code > Run Script`)

```python
import sys
import subprocess

subprocess.call([sys.executable, "-m", "pip", "install", "pyvista"])
```

If it still doesn't work, can you show what is displayed in Blender's console? (`Window > Toggle System Console`)

**Comment by engineeraid-austin** [comment]
Hi there, 

I am running into the same issue. I tried executing the script as you outlined. Below is an output is what I received from the console log. 

```
[notice] A new release of pip is available: 23.2.1 -> 24.1.2
[notice] To update, run: C:\Program Files\Blender Foundation\Blender 4.1\4.1\python\bin\python.exe -m pip install --upgrade pip
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pyvista in c:\users\ahowe\appdata\roaming\python\python311\site-packages (0.44.0)
Requirement already satisfied: matplotlib>=3.0.1 in c:\users\ahowe\appdata\roaming\python\python311\site-packages (from pyvista) (3.9.1)
Requirement already satisfied: numpy>=1.21.0 in c:\program files\blender foundation\blender 4.1\4.1\python\lib\site-packages (from pyvista) (1.24.3)
Requirement already satisfied: pillow in c:\users\ahowe\appdata\roaming\python\python311\site-packages (from pyvista) (10.4.0)
Requirement already satisfied: pooch in c:\users\ahowe\appdata\roaming\python\python311\site-packages (from pyvista) (1.8.2)
Requirement already satisfied: scooby>=0.5.1 in c:\users\ahowe\appdata\roaming\python\python311\site-packages (from pyvista) (0.10.0)
Requirement already satisfied: vtk in c:\users\ahowe\appdata\roaming\python\python311\site-packages (from pyvista) (9.3.1)
Requirement already satisfied: typing-extensions in c:\users\ahowe\appdata\roaming\python\python311\site-packages (from pyvista) (4.12.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\ahowe\appdata\roaming\python\python311\site-packages (from matplotlib>=3.0.1->pyvista) (1.2.1)
Requirement already satisfied: cycler>=0.10 in c:\users\ahowe\appdata\roaming\python\python311\site-packages (from matplotlib>=3.0.1->pyvista) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\ahowe\appdata\roaming\python\python311\site-packages (from matplotlib>=3.0.1->pyvista) (4.53.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\ahowe\appdata\roaming\python\python311\site-packages (from matplotlib>=3.0.1->pyvista) (1.4.5)
Requirement already satisfied: packaging>=20.0 in c:\users\ahowe\appdata\roaming\python\python311\site-packages (from matplotlib>=3.0.1->pyvista) (24.1)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\ahowe\appdata\roaming\python\python311\site-packages (from matplotlib>=3.0.1->pyvista) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\ahowe\appdata\roaming\python\python311\site-packages (from matplotlib>=3.0.1->pyvista) (2.9.0.post0)
Requirement already satisfied: platformdirs>=2.5.0 in c:\users\ahowe\appdata\roaming\python\python311\site-packages (from pooch->pyvista) (4.2.2)
Requirement already satisfied: requests>=2.19.0 in c:\program files\blender foundation\blender 4.1\4.1\python\lib\site-packages (from pooch->pyvista) (2.27.1)
Requirement already satisfied: six>=1.5 in c:\users\ahowe\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.7->matplotlib>=3.0.1->pyvista) (1.16.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\program files\blender foundation\blender 4.1\4.1\python\lib\site-packages (from requests>=2.19.0->pooch->pyvista) (1.26.8)
Requirement already satisfied: certifi>=2017.4.17 in c:\program files\blender foundation\blender 4.1\4.1\python\lib\site-packages (from requests>=2.19.0->pooch->pyvista) (2021.10.8)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\program files\blender foundation\blender 4.1\4.1\python\lib\site-packages (from requests>=2.19.0->pooch->pyvista) (2.0.10)
Requirement already satisfied: idna<4,>=2.5 in c:\program files\blender foundation\blender 4.1\4.1\python\lib\site-packages (from requests>=2.19.0->pooch->pyvista) (3.3)

[notice] A new release of pip is available: 23.2.1 -> 24.1.2
[notice] To update, run: C:\Program Files\Blender Foundation\Blender 4.1\4.1\python\bin\python.exe -m pip install --upgrade pip
```

Then I try to enable the add-on again and receive this traceback:

```
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\modules\addon_utils.py", line 376, in enable
    mod = importlib.import_module(module_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\python\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\ahowe\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blender-tpms-main\__init__.py", line 14, in <module>
    from . import ui
  File "C:\Users\ahowe\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blender-tpms-main\ui.py", line 5, in <module>
    import pyvista as pv
ModuleNotFoundError: No module named 'pyvista'
```

**Comment by engineeraid-austin** [comment]
Update: I closed blender and re-opened the app. I tried to 'check' the add-on again and it worked this time. Not sure why that fixed the issue but it did. Hopefully that helps someone else.

**Comment by kmarchais** [comment]
Thank you for reporting it!
